---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: mount network file storage
  ansible.builtin.mount:
    path: "{{ network_mount.path }}"
    src: "{{ network_mount.server }}:{{ network_mount.volume }}"
    opts: "nofail,ro"
    fstype: nfs
    state: mounted
  loop: "{{ network_mounts }}"
  loop_control:
    loop_var: "network_mount"